// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define stimulate_HPPC_SixDPos_BODY

/************************************************************
 SixDPos class body
 ************************************************************/

// include associated header file
#include <iostream>
#include "SixDPos.h"

SixDPos::SixDPos(Json::Value _json_value)
{
    this->deserialize_from_json(_json_value);
}


Json::Value* SixDPos::serialize_to_json()
{
	Json::Value* json_pose = new Json::Value();
	(*json_pose)["m_x"] = this->get_X();
	(*json_pose)["m_y"] = this->get_Y();
	(*json_pose)["m_z"] = this->get_Z();
	(*json_pose)["m_a"] = this->get_A();
	(*json_pose)["m_b"] = this->get_B();
	(*json_pose)["m_c"] = this->get_C();
	return json_pose;
}

void SixDPos::deserialize_from_json(Json::Value json_value)
{
    this->set_position({json_value["m_x"].asDouble(), json_value["m_y"].asDouble(), json_value["m_z"].asDouble(), json_value["m_a"].asDouble(), json_value["m_b"].asDouble(), json_value["m_c"].asDouble()});
}


/************************************************************
 End of SixDPos class body
 ************************************************************/
